/*
*	Copyright 2009 Griffin Software
*
*	Licensed under the Apache License, Version 2.0 (the "License");
*	you may not use this file except in compliance with the License.
*	You may obtain a copy of the License at
*
*		http://www.apache.org/licenses/LICENSE-2.0
*
*	Unless required by applicable law or agreed to in writing, software
*	distributed under the License is distributed on an "AS IS" BASIS,
*	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*	See the License for the specific language governing permissions and
*	limitations under the License. 
*/

import "oaidl.idl";
import "ocidl.idl";
midl_pragma warning(disable: 2015)
import "vsshell.idl";
midl_pragma warning(default: 2015)

[
	uuid(694BCCDA-B2B0-4A97-BB4B-E7B128B05D76),
	version(1.0),
	helpstring("MetalScroll 1.0 Type Library")
]
library MetalScrollLib
{
	importlib("stdole2.tlb");
	[
		uuid(4982020C-DFD7-4928-A1C7-DA5F154973BC),
		helpstring("Connect Class")
	]
	coclass Connect
	{
		[default] interface IUnknown;
	};
	[
		uuid(4388225E-8798-4064-A4D7-1E2B1F4B52CF),
		helpstring("MetalScrollPackage Class")
	]
	coclass MetalScrollPackage
	{
		[default] interface IVsPackage;
	};
	[
		uuid(DB618CA2-6EEC-4ABB-98E2-61E2574F3E78),
		helpstring("EditCmdFilter Class")
	]
	coclass EditCmdFilter
	{
		[default] interface IOleCommandTarget;
	};
};
